services:
  backend:
    build: ./backend
    container_name: vayuguard-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: vayuguard-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: